import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on April 17, 2007, 5:42 PM
 */

/**
 *
 * @author Howard
 */
public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(XmlData.XmlDataSuite.suite());
        suite.addTest(swdemo.SwdemoSuite.suite());
        return suite;
    }
    
}
