/*
 * ComMgrSuite.java
 * JUnit based test
 *
 * Created on April 17, 2007, 5:37 PM
 */

package ComMgr;

import junit.framework.*;

/**
 *
 * @author Howard
 */
public class ComMgrSuite extends TestCase {
    
    public ComMgrSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ComMgrSuite");
        suite.addTest(ComMgr.ItypesTest.suite());
        suite.addTest(ComMgr.IforwardTest.suite());
        suite.addTest(ComMgr.IcallBackTest.suite());
        suite.addTest(ComMgr.SysProcTest.suite());
        suite.addTest(ComMgr.DefProcTest.suite());
        suite.addTest(ComMgr.ComMgrTest.suite());
        suite.addTest(ComMgr.LogTraceTest.suite());
        suite.addTest(ComMgr.ArgumentTest.suite());
        return suite;
    }
    
}
