/*
 * XmlDataSuite.java
 * JUnit based test
 *
 * Created on April 17, 2007, 5:42 PM
 */

package XmlData;

import junit.framework.*;

/**
 *
 * @author Howard
 */
public class XmlDataSuite extends TestCase {
    
    public XmlDataSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("XmlDataSuite");
  //      suite.addTest(mySplitPaneDemoTest.suite());
  //      suite.addTest(myDemoTest.suite());
 //      suite.addTest(myTabbedPaneDemoTest.suite());
 //       suite.addTest(myComboBoxDemoTest.suite());
 //       suite.addTest(myDemo1Test.suite());
        return suite;
    }
    
}
